baseURL = 'https://www.roboticdinosaur.co.uk/'
languageCode = 'en-gb'
title = 'RoboticDinosaur'
theme= 'hugo-coder'

[pagination]
pagerSize = 20

[services]
#[services.disqus]
#shortname = "roboticdinosaur"

[markup.highlight]
style = "github-dark"

[params]
  author = "RoboticDinosaur"
  info = "A journey through cyber security"
  description = "A personal journey through the world of pentesting and security"
  keywords = ["Pentesting", "Security", "Hacking"]
  avatarurl = "images/roboticdinosaur.svg"

  since = 2025

  enableTwemoji = true

  colorScheme = "light"
  hidecolorschemetoggle = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

#[[params.social]]
#  name = "mastodon"
#  icon = "fa-brands fa-mastodon"
#  weight = 1
#  url = "https://indieweb.social/@roboticdinosaur"

[[params.social]]
  name = "github"
  icon = "fa-brands fa-github"
  weight = 2
  url = "https://github.com/roboticdinosaur"

#[[menu.main]]
#  name = "About"
#  weight = 2
#  url = "/about/"

[[menu.main]]
  name = "Posts"
  weight = 1
  url = "/posts/"
#
#[[menu.main]]
#  name = "Projects"
#  weight = 2
#  url = "/projects/"
#
#[[menu.main]]
#  name = "Contact"
#  weight = 3
#  url = "/contact/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
